# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss,templates}/**/*"
  # Paths to font file directories to be copied
  fonts:
    - "node_modules//@fortawesome/fontawesome-pro/webfonts/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules"
    - "node_modules/font-awesome/scss"
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "node_modules"
    - "src/assets/js/app.js"
